# This file was generated by GoReleaser. DO NOT EDIT.
cask "dflow" do
  desc "Manage your daily development flow with ease."
  homepage "https://github.com/ottobitsystems/dflow"
  version "0.0.3-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dflow"

  on_macos do
    on_intel do
      url "https://github.com/OttobitSystems/dflow/releases/download/v0.0.3-alpha/dflow_Darwin_x86_64.tar.gz"
      sha256 "aa697d45695b8ed91bfd2e2f28789cfb74ca1c526bc27d1c9eaba240dfdb3ea6"
    end
    on_arm do
      url "https://github.com/OttobitSystems/dflow/releases/download/v0.0.3-alpha/dflow_Darwin_arm64.tar.gz"
      sha256 "dbef8cc8e9afb3f9aec48d52543c73b1fac9e41bba9dee7611529839adcc4179"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/OttobitSystems/dflow/releases/download/v0.0.3-alpha/dflow_Linux_x86_64.tar.gz"
      sha256 "6969ea8695963e45758b7e8f48632f42355e6934bd2302d9cc561ffd0c90883b"
    end
    on_arm do
      url "https://github.com/OttobitSystems/dflow/releases/download/v0.0.3-alpha/dflow_Linux_arm64.tar.gz"
      sha256 "d229bc2a3a173f021c90c7bcd575736c9f8f73e3305991a6c22a84582b0c69f9"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dflow"]
    end
  end

  # No zap stanza required
end
